config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  root 'sheets#index'

  resources :sheets, :things

  post "things/create"
  post "things/update"

end

app/models/thing.rb
class Thing < ActiveRecord::Base
  belongs_to :user
  
  def self.search(search)
    if search
      where('content LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :things

  def self.emailsearch(search)
    if search
      where('email LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    build_resource(sign_up_params)

    if resource.save
        yield resource if block_given?
        if resource.active_for_authentication?
            set_flash_message :notice, :signed_up if is_flashing_format?
            sign_up(resource_name, resource)
            respond_with resource, location: after_sign_up_path_for(resource)
        else
            set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
            expire_data_after_sign_in!
            respond_with resource, location: after_inactive_sign_up_path_for(resource)
        end
    else
        clean_up_passwords resource
        resource.errors.full_messages.each {|x| flash[x] = x} # Rails 4 simple way
        redirect_to root_path
    end
  end
end 

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  def index
    @things = Thing.all
    if user_signed_in?
      @mythings = current_user.things
    end
  end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  def index
    user = User.emailsearch(params[:search]).first
    if user.nil?
      @things = Thing.search(params[:search])
    else
      @things = (Thing.search(params[:search]) + user.things).uniq
    end
    if user_signed_in?
      @mythings = current_user.things
    end
  end
  def create
    if user_signed_in?
      @thing = Thing.new(thing_params)
      respond_to do |format|
        if @thing.save
          @thing = Thing.new
          @things = Thing.all
          flash.now[:notice] = "Thing added"
          format.js
        else
          flash.now[:alert] = "There was a problem adding your thing, please try again"
          render "partials/flashes"
        end
      end
    else
      flash.now[:alert] = "You have to be logged in to add things"
      render "partials/flashes"
    end
  end
  def update
    if user_signed_in?
      @thing = Thing.find(params[:id])
      respond_to do |format|
        if @thing.update(thing_params)
          @thing = Thing.new
          @things = Thing.all
          flash.now[:notice] = "Thing updated"
          format.js
        else
            flash.now[:alert] = "There was a problem editing the thing, please try again"
            render "partials/flashes"
        end
      end
    else
      flash.now[:alert] = "You have to be logged in to edit things"
      render "partials/flashes"
    end
  end
  def destroy
    if user_signed_in?
      @thing = Thing.find(params[:id])
      @thing.destroy
      respond_to do |format|
        @thing = Thing.new
        @things = Thing.all
        flash.now[:notice] = "Thing deleted"
        format.js
      end
    else
      flash.now[:alert] = "You have to be logged in to delete things"
      render "partials/flashes"
    end
  end

  private
    def thing_params
      params.permit(:content, :user_id, :id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/home/index.html.haml
#slide1
  %div
    #christmas_tree
    #snowflakes1
    #snowflakes2
    %h2 MERRY
    %h1 CHRISTMAS
    #divider
    %h3 HAPPY NEW YEAR
    #ribbon
    #new_year
#slide2
  %div
    %div
      %h3 “Then the Grinch thought of something he hadn't before! What if Christmas, he thought, doesn't come from a store. What if Christmas...perhaps...means a little bit more!”
      %img{:align => "left", :src => "img/dr-seuss.png"}/
      %h4 Dr. Seuss
#slide3
  %div
    %div
      %h3 “I truly believe that if we keep telling the Christmas story, singing the Christmas songs, and living the Christmas spirit, we can bring joy and happiness and peace to this world.”
      %img{:align => "left", :src => "img/norman.png"}/
      %h4 Norman Vincent Peale
#slide4
  %div
    %div
      %h3 “Christmas doesn't come from a store, maybe Christmas perhaps means a little bit more....”
      %img{:align => "left", :src => "img/dr-seuss.png"}/
      %h4 Dr. Seuss
#slide5
  %div
    %div
      %h3 “My idea of Christmas, whether old-fashioned or modern, is very simple: loving others. Come to think of it, why do we have to wait for Christmas to do that?”
      %img{:align => "left", :src => "img/bob.png"}/
      %h4 Bob Hope
    #copyright
      %a{:href => "http://www.1stwebdesigner.com/"} Copyright 1stwebdesigner.com
:javascript
  console.log($(window).height());
  console.log($(window).scrollTop());
  console.log($('#slide2').offset().top);

app/views/layouts/application.html.haml
%html
  %head
    %link{href: "http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css", rel: "stylesheet", type: "text/css"}/
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    #flash
      =render "partials/flashes"
    =render "partials/loginpage"
    =yield

app/views/partials/_flashes.html.haml
-if !flash.empty?
  -if notice
    .popup.pup-notice
      -flash.each do |name, msg|
        =content_tag :div, msg, class: name
      %button.btn.btn-notice OK
  -else
    .popup.pup-alert
      -flash.each do |name, msg|
        =content_tag :div, msg, class: name
      %button.btn.btn-alert OK

app/views/partials/_login.html.haml
= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
  .form-group
    = f.email_field :email, autofocus: true, placeholder: "email", class: "form-control"
  .form-group
    = f.password_field :password, autocomplete: "off", placeholder: "password", class: "form-control"
  = f.submit "Sign in", class: "btn btn-login"
  - if devise_mapping.rememberable?
    = f.check_box :remember_me
    = f.label :remember_me

app/views/partials/_loginpage.html.haml
#loginsheet
  .loginbutton
    -if user_signed_in?
      %span#changer
        =current_user.email.slice(0..(current_user.email.index('@')-1))
      =link_to destroy_user_session_path, method: :delete do
        <span></span>
    -else
      login
  .logincontent
    .lefthalf
      =render "partials/login"
    .righthalf
      =render "partials/register"

app/views/partials/_register.html.haml
= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f|
  = devise_error_messages!
  .form-group
    = f.email_field :email, placeholder: "email", class: "form-control"
  .form-group
    = f.password_field :password, autocomplete: "off", placeholder: "password", class: "form-control"
  .form-group
    = f.password_field :password_confirmation, autocomplete: "off", placeholder: "confirm password", class: "form-control"
  = f.submit "Sign up", class: "btn btn-login"

app/views/partials/flashes.js.erb
$("#flash").html("<%= escape_javascript(render partial: '/partials/flashes') %>");

app/views/sheets/index.html.haml
.book
  .one.first.sheet
    .sheetbutton
      one
    .sheetcontent
      .element
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque massa justo, mollis lobortis massa vitae, maximus pulvinar magna. In aliquet purus eget efficitur suscipit. Donec sollicitudin nunc et orci pellentesque, eget commodo ex interdum. Nunc vel magna tincidunt, sagittis nibh ac, dapibus metus. Donec aliquam diam ornare hendrerit mattis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris ac felis eu mi maximus pharetra luctus ac ante. Ut eu condimentum nisl, sit amet luctus quam. Aenean sed ligula in nisi vehicula tristique. Aliquam eget metus quam.
  .two.second.sheet
    .sheetbutton
      two
    .sheetcontent
      =render "things/index"
  .three.third.sheet
    .sheetbutton
      three
    .sheetcontent
  .four.fourth.sheet
    .sheetbutton
      four
    .sheetcontent
  .five.fifth.sheet
    .sheetbutton
      five
    .sheetcontent

app/views/things/_index.html.haml
%h3 All the Things
= form_tag things_path, method: 'get', id: "things_search" do
  .form-group.has-feedback.search-bar
    %label.control-label Search
    = text_field_tag :search, params[:search], {autocomplete: "off", type: "input", placeholder: "start typing to search...", class: "form-control", title: "search by things or authors"}
    %i.fa.fa-search.form-control-feedback
#things
  =render "things/list"

app/views/things/_list.html.haml
-@things.each do |e|
  %form{action: "/things/update", method: "post", "data-remote" => "true"}
    .form-group.indentleft
      =hidden_field_tag "authenticity_token", form_authenticity_token
      =hidden_field_tag  "id", e.id
      -if user_signed_in?
        =hidden_field_tag  "user_id", current_user.id
      .input-group
        %input.form-control{name: "content", value: e.content}
        %span.input-group-btn
          =link_to 'delete', {controller: "things", action: "destroy", id: e.id}, method: "delete", data: {confirm: "Are you sure?"}, remote: true, class: "btn btn-delete"
          %button.btn.btn-change{type: "submit"} change
%form{action: "/things/create", method: "post", "data-remote" => "true"}
  .form-group.indentleft
    =hidden_field_tag "authenticity_token", form_authenticity_token
    -if user_signed_in?
      =hidden_field_tag  "user_id", current_user.id
    .input-group
      %input.form-control{name: "content", placeholder: "describe the thing..."}
      %span.input-group-btn
        %button.btn.btn-add{type: "submit"} add

app/views/things/create.js.erb
$("#things").html("<%= escape_javascript(render partial: '/things/list') %>");
$("#flash").html("<%= escape_javascript(render partial: '/partials/flashes') %>");

app/views/things/destroy.js.erb
$("#things").html("<%= escape_javascript(render partial: '/things/list') %>");
$("#flash").html("<%= escape_javascript(render partial: '/partials/flashes') %>");

app/views/things/index.js.erb
$("#things").html("<%= escape_javascript(render partial: '/things/list') %>");
$("#flash").html("<%= escape_javascript(render partial: '/partials/flashes') %>");

app/views/things/update.js.erb
$("#things").html("<%= escape_javascript(render partial: '/things/list') %>");
$("#flash").html("<%= escape_javascript(render partial: '/partials/flashes') %>");